### ISSUE TITLE
Download option not showing

### ISSUE THREAD

**Issue by yashwanth099** [pidugusundeep/acloudguru-Video-Downloader#1]
it also installing adware in in the browser

**Comment by pidugusundeep** [comment]
😧  I do not have anything in my code of that sort. Pretty sure it's to do with your browser and other extensions that you have installed. I have recently [updated](https://chrome.google.com/webstore/detail/a-cloud-guru-video-downlo/hdnlbojfcclonhkemkfmllflgoebfmfe?hl=en&authuser=0) the extension feel free to use that as well.
